steps:
# Create bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gsutil mb -l us-central1 gs://terraform-bucket-nishant-12345

# Create VM
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute networks create terraformvpc-nishant --subnet-mode=auto || echo "Network already exists"
      gcloud compute instances create terraform-instance-nishant \
        --zone=us-central1-c \
        --machine-type=f1-micro \
        --network=terraformvpc-nishant \
        --image=debian-11 \
        --image-project=debian-cloud

timeout: 600s
